### ISSUE TITLE
Image saved twice when using quality

### ISSUE THREAD

**Issue by RocKhalil** [react-native-community/react-native-image-picker#1064]
### Description

Whenever I set the quality of the image different than 1, the image gets saved on the device with both full resolution and resized one.

### How to repeat issue and example

Here are my options:

```
    var options = {
      title: 'Test',
      mediaType: 'image',
      quality: 0.2,
      cameraType: "front",
      noData: true,
      allowsEditing: false
    };
```

### Solution

Not sure what should be done here, I'm even not sure whether it's something related to the library or Core Android itself.

### Additional Information

* React Native version: "0.55.3"
* Platform: Android
* Development Operating System: MacOS
* Dev tools: Android built SDK

**Comment by fuavix** [comment]
Yes,  it's something related to the library! Because these pictures may be compressed by the library. And it did not delete the original image.So you can delete the original picture by yourself. But, The response of this library does not find the original path ！

Fix：Modify ImagePickerModule.java 
Search `BitmapFactory.decodeFile(imageConfig.original.getAbsolutePath(), options);`
You can find the original path. 
insert `String pathOri = imageConfig.original.getAbsolutePath()`
change `updatedResultResponse(uri, imageConfig.original.getAbsolutePath())` to `updatedResultResponse(uri, imageConfig.original.getAbsolutePath(), pathOri)`.
Add code `responseHelper.putString("pathOri", originalPath);` in function 'updatedResultResponse'

**Comment by petergaultney** [comment]
This is a problem for me as well.  There are two copies made, but only one path (of the lower quality image) returned, so the filesystem gets cluttered with extra, full-size images that I cannot reliably get rid of.

**Comment by agrass** [comment]
This still a problem in the last version, anyone already solved this??

**Comment by wallace7souza** [comment]
I think the response object is missing the field origURL but it's not available in android version. 
To avoid duplicate the image, I'm tryinn to reduce the image using this lib https://github.com/bamlab/react-native-image-resizer

**Comment by AnurajDev** [comment]
Facing this issue. It would be great if somebody can come up with a solution.

**Comment by rynvva** [comment]
can anyone reopen this? still happening to me

**Comment by ganholete** [comment]
+1

**Comment by 15110011** [comment]
same here 
ver: "react-native-image-picker": "^2.3.3"

**Comment by vikas-quant** [comment]
This issue hasn't been resolved yet?

**Comment by mariasyedd** [comment]
This issue is still relevant
