### ISSUE TITLE
App freezes on selecting large size images.

### ISSUE THREAD

**Issue by NainalChauhan** [react-native-community/react-native-image-picker#1073]
When I select a image from library which is 15MB in size, then the app freezes and then crashed without returning any response, not returning any error.

**Comment by RimochPayEm** [comment]
Experiencing the same issue. for me it also happens on the camera side. after taking a photo and selecting 'v' the app freezes and restarts. Happens on android devices with high quality cameras (One Plus 6T, Pixel 2, Samsung S9). 
For now bug only happens on android and not on IOS or emulator devices.
here is my options: (I tried to rescale the image in order to prevent the crash but no luck)

`options = {
        storageOptions: {
            skipBackup: true,
            path: 'images',
        },
        maxWidth: 1200,
        maxHeight: 800,
        quality: 0.9,
        noData: true,
    };`

Would love for some input

**Comment by Rimoch** [comment]
Experiencing the same issue. for me it also happens on the camera side. after taking a photo and selecting 'v' the app freezes and restarts. Happens on android devices with high quality cameras (One Plus 6T, Pixel 2, Samsung S9). 
For now bug only happens on android and not on IOS or emulator devices.
here is my options: (I tried to rescale the image in order to prevent the crash but no luck)

`options = {
        storageOptions: {
            skipBackup: true,
            path: 'images',
        },
        maxWidth: 1200,
        maxHeight: 800,
        quality: 0.9,
        noData: true,
    };`

Would love for some input

**Comment by Augustach** [comment]
Hi all,
I have a same problem when use ImagePickerService.showImagePicker and I found a exception using logcat.

```
AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 54702364 byte allocation with 4500096 free bytes and 4MB until OOM
AndroidRuntime:        at android.util.Base64.encode(Base64.java:534)
AndroidRuntime:        at android.util.Base64.encode(Base64.java:494)
AndroidRuntime:        at android.util.Base64.encodeToString(Base64.java:456)
AndroidRuntime:        at com.imagepicker.ImagePickerModule.getBase64StringFromFile(ImagePickerModule.java:690)
AndroidRuntime:        at com.imagepicker.ImagePickerModule.updatedResultResponse(ImagePickerModule.java:535)
AndroidRuntime:        at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:443)
AndroidRuntime:        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:253)
```

As workaround I invoke ImagePickerService.showImagePicker with options `{noData: true}`

Probably it will help you.

**Comment by Rimoch** [comment]
As posted in my options object, i did flag noData to true. Still didnt help. I ended up lowering the quality to 0.7 on android in order it to stop crashing. Although I really don't really like this solution.

**Comment by AnurajDev** [comment]
Same issue. Tried reducing quality also. No luck yet.
