### ISSUE TITLE
Define the file name on storageOptions

### ISSUE THREAD

**Issue by iuribtt** [react-native-community/react-native-image-picker#1267]
First of all thanks for this great library. It is very useful.

# Feature Request
Option to define the not only the path, also the file name to be save on storage. 

## Why it is needed

When it is need to store a profile picture, we can use the user ID. Therefore, it will be easy to find the foto desired among the other photos.

Regards,
Iúri

**Comment by TheRakeshPurohit** [comment]
yup ! it is the most needed feature. In Many projects we need to save by the customized name like userID or something unique related to user. so that accessing user photo along with other profile details can be done without extra efforts. 

there are some libraries that allows to reaname and move to desired directory but that needs extra efforts. 

If this tiny attribute "fileName" as string is added to the storageOptions object then it will be very awesome.

we need this feature. dont close this repo. remove the stale label.

I'm struggling with this issue from last somedays.

**Comment by TheRakeshPurohit** [comment]
Is anything happening about this issue ?
