### ISSUE TITLE
Is there any way to set duration limit for video that picked from gallery

### ISSUE THREAD

**Issue by brendan1809** [react-native-community/react-native-image-picker#1279]
# Question
Is there any way to set duration limit for video that picked from gallery??

**Comment by maomeiqi** [comment]
I also want to know

**Comment by sumudu-dewasurendra** [comment]
`const options = {
        title: 'Video Picker',
        takePhotoButtonTitle: 'Take Video...',
        mediaType: 'video',
        videoQuality: Platform.OS == 'ios'?'high':'low',
        durationLimit: 60,
        allowsEditing: true
        }`

`        ImagePicker.showImagePicker(options, (response) => {
})
`

**Comment by cnairi** [comment]
Hi everyone,
I'm facing the same issue on Android devices only // working perfectly on iOS and when making a video from camera
I've already implemented allowsEditing: true and durationLimit 20

I'm using 0.28.0 version, because I can't upgrade to react-native 0.60 for the moment.

Does anyone have a workaround please ?

Thanks a lot.

**Comment by watadarkstar** [comment]
Bump this is still something the community needs
