### ISSUE TITLE
Android Camera doesn't open and error "Couldn't get file path for photo" at version 2.3.0

### ISSUE THREAD

**Issue by taduyde** [react-native-community/react-native-image-picker#1286]
# Bug

I got the issue when I choose use camera the message error is: "Couldn't get file path for photo"

## Environment info

- React native 0.61
- Android device: (Samsung galaxy s7 (v8)) 

Library version: 2.3.0

**Comment by samzer** [comment]
Same is happening for me. If you choose the camera for the first time, it gives this error but if you choose a photo from the library and then choose the camera - It works then.

**Comment by janva255** [comment]
So the problem is that I was using cameraRoll option to save photos with camera but it didn't ask permission to write.

What I changed for it to work:

https://github.com/react-native-community/react-native-image-picker/blob/master/android/src/main/java/com/imagepicker/ImagePickerModule.java#L644

Adding write external storage permission.

`
case REQUEST_PERMISSIONS_FOR_CAMERA:
            PERMISSIONS = new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.CAMERA};
            break;
`

It should be modified here too
https://github.com/react-native-community/react-native-image-picker/blob/master/android/src/main/java/com/imagepicker/ImagePickerModule.java#L586

`
      case REQUEST_PERMISSIONS_FOR_CAMERA:
        permissionsGranted = cameraPermission == PackageManager.PERMISSION_GRANTED
&& writePermission == PackageManager.PERMISSION_GRANTED;
        break;
`

I don't know android but I will try to make a pr for this. I will have to do some logic for this permission to be only added when cameraRoll option is on.

**Comment by iqbalfaisal** [comment]
@janva255 Thanks Man. It really help me. I make PR for this bug. Thank again.

**Comment by RnbWd** [comment]
@janva255 thanks for looking into this, I'm going to test your PR locally

**Comment by williamgoodhew** [comment]
@janva255 do we have to add those settings to the app file or the node module file?

**Comment by janva255** [comment]
@williamgoodhew Check the pr, it has been merged already the fix
