### ISSUE TITLE
Image Picker not working on Android (linking problem)

### ISSUE THREAD

**Issue by yesIamFaded** [react-native-community/react-native-image-picker#1353]
I cant use the image-picker because no version is really working. I am using rn0.62 and autolinking doesnt seem to work properly. 

![Screenshot_1587979664](https://user-images.githubusercontent.com/48751859/80356765-35e7e900-887a-11ea-9d6f-76987954970e.png)

Unistall the latest version
npm uninstall react-native-image-picker
Installed version 0.28.0
npm install react-native-image-picker@0.28.0 --save
react-native link react-native-image-picker

the fixx above also does NOT work for me! Also I think its weird that this is still bugged because it is known for so long.

**Comment by hjwlpjr** [comment]
Hi, do you managed to get this working on? strange, same thing happen to me. What make it more strange is because I had 2 project with same environment

RN 0.62
image picker v2.3.1

on one app it working fine, but on another project it just fail on android version with the error ImagePickerManager is null

**Comment by yesIamFaded** [comment]
@hjwlpjr actually I did not.. I rebuild my whole app in expo and without touching my code it was working like a charm 😊  I think its sick how good stuff works in expo but getting this to run in a bare react native app is a pain in the a$$ 😄
