### ISSUE TITLE
[Android] Allow to set both image and video mediaTypes

### ISSUE THREAD

**Issue by akania** [react-native-community/react-native-image-picker#379]
Can we please add support to select both image and video on Android?
It seems that its possible by providing multiple types to setType, also couple other solutions is mentioned over the web..

**Comment by yfuks** [comment]
**PR** are welcome

**Comment by proProbe** [comment]
Im currently trying to implement this. I've forked the library and started but am currently stuck on trying to get the correct filepath. The fork is located here `https://github.com/proProbe/react-native-image-picker/blob/master/android/src/main/java/com/imagepicker/ImagePickerModule.java`. The problem is basically on line `https://github.com/proProbe/react-native-image-picker/blob/master/android/src/main/java/com/imagepicker/ImagePickerModule.java#L376` where the path is `null`. The code am able to pick out images or videos but gives an `URI` with `content:/` instead of `file://`. Im also quite noob at java/android-native programming so any suggestions would be appreciated!
