### ISSUE TITLE
Video Duration Limit option not working

### ISSUE THREAD

**Issue by larryranches** [react-native-community/react-native-image-picker#534]
I'm setting the durationLimit upload to be at 5 seconds but the picker allows videos that are greater than 5 seconds like 30 seconds. 

Is this a bug? What is the expected behavior when a durationLimit is set and a user tries to upload a video greater? Is there supposed to be a warning, etc?

```    
const options = {
      mediaType: 'video',
      videoQuality: 'medium',
      durationLimit: 5,
    }
```

**Comment by juddey** [comment]
Hey there, great package! :1st_place_medal: I was working with this today and thought I would share what I had found since there was an issue open. In some situations the durationLimit worked for me and in others, not.

- iphone 6 running ios 10.2 on physical device - phone shows a message after the durationLimit saying 'The limit of the video has been reached' + video stops recording
- Android Nexus 5X emulator, android 6.0 - emulator stops recording after the specified time (theres a little countdown at the top of the screen to let you know how far there is to go)
- Android Plus One physical device, android 5.1.1 (cyanogen) - the limit is not enforced (ie same behavior as OP).

Gotta try on an android 7 device so I'll post back results here when I do that.

**Comment by larryranches** [comment]
Seems like this works for when capturing a video and setting a duration limit. I guess the durationLimit option doesn't handle when uploading an existing video from a mobile device that is greater than the durationLimit.

Would this be feature request?

**Comment by tsugitta** [comment]
I think the issue occurred because the ImagePicker's option `allowedEditing` must be `true` to trim a video.

```js
const options = {
  mediaType: 'video',
  videoQuality: 'medium',
  durationLimit: 5,
  allowsEditing: true
}
```

**Comment by BaderSerhan** [comment]
@tsugitta thank you! worked for me like a charm

**Comment by BaderSerhan** [comment]
hey, i am facing the same problem: the component shows the cropped video, yet it uploads the entire video, any solution yet?

**Comment by alisa-hui** [comment]
安卓上面录视频的时候不会提示视频已达最大时长

**Comment by anwaar931** [comment]
I am facing the same issue.

^https://github.com/react-native-community/react-native-image-picker/issues/534#issuecomment-479383975 
>  When the video is recorded on Android, the video will not be prompted for the maximum ### duration.

**Comment by Nihaal-Aftab** [comment]
> I think the issue occurred because the ImagePicker's option `allowsEditing` must be `true` to trim a video.
> 
> ```js
> const options = {
>   mediaType: 'video',
>   videoQuality: 'medium',
>   durationLimit: 5,
>   allowsEditing: true
> }
> ```

well that's only for iOS, not working on android.

**Comment by lokeshrezo** [comment]
Hi I am recording the video durationLimit is not working for me in android device but working fine in IOS. can you help me how to fix for android?
