### ISSUE TITLE
[IOS] fileName undefined

### ISSUE THREAD

**Issue by aldente05** [react-native-community/react-native-image-picker#616]
### Description
when i get response.uri is success, but when response.fileName on ios 10
the fileName is undefined
### Additional Information

* React Native version: "react-native": "0.44.0"
* Platform: iOS
* Development Operating System:  developing on MacOS Sierra
* Dev tools: Atom

**Comment by prakashw3expert** [comment]
same issue for me

**Comment by summmmer** [comment]
same issue for me

**Comment by ZXIAOY** [comment]
in my callback, i can't get fileName value on IOS, but response.data still have value.
there is not such problem on android.

**Comment by sabun123** [comment]
I had this issue as well using react-native-image-picker version 0.28.0 on iOS devices using iOS 12.

I would get response.fileName being undefined when using the camera:
```javascript
ImagePicker.launchCamera(options, (response) => this.imageHandler(response, type));
```
However, it worked fine for images from the gallery:
```javascript
ImagePicker.launchImageLibrary(options, (response) => this.imageHandler(response, type));
```

The undefined value was causing my formData to pass null as the name when passing up to the backend, and break things when using the image directly from camera. 

Workaround was to grab the fileName from the uri using some string manipulations in javascript.
```javascript
let imgName = fileName;
        if(typeof fileName === "undefined"){
            var getFilename = uri.split("/");
            imgName = getFilename[getFilename.length - 1];
        }
``` 

Since the uri usually looks something like this on iOS when using the camera:
```
"/ABA3C2B9-81AA-4A3C-AF12-52EE782DDF02/Documents/images/C9E9ECE5-441A-44D9-9E7E-527480B2A878.jpg""
```
So the above code just separates everything where there's a ```/``` and finally, grab the one at the very end which in our case is the filename (which in the above example would be ```C9E9ECE5-441A-44D9-9E7E-527480B2A878.jpg```).

So my final imageHandler looks something like this:
```javascript
imageHandler = ({ uri, fileSize, fileName }, type) => {
    if(uri){
      if(fileSize < maxSize) {
        let imgName = fileName;
        if(typeof fileName === "undefined"){
            // on iOS, using camera returns undefined fileName. This fixes that issue, so API can work.
            var getFilename = uri.split("/");
            imgName = getFilename[getFilename.length - 1];
        }
        this.setState({ [type]: uri, imageName: imgName, setted: true });
      } else {
        Alert.alert('Error', 'This image is too large');
      }
    }
  };
```

Not the most ideal setup, but works in the interim for iOS devices.

**Comment by issaghaBarry** [comment]
```
var getFilename = uri.split("/");
imgName = getFilename[getFilename.length - 1]
```
hello, do you know how to get original filename of image, not like **5a6e2d93-c96c-4559-997d-0a7bc5cecf32.jpg**

**Comment by ShahriarKh** [comment]
> 
> 
> ```
> var getFilename = uri.split("/");
> imgName = getFilename[getFilename.length - 1]
> ```
> 
> hello, do you know how to get original filename of image, not like **5a6e2d93-c96c-4559-997d-0a7bc5cecf32.jpg**

Hey man! I guess it'll be better to open a new issue.
