### ISSUE TITLE
Android runtime permission - should show system dialog at least twice

### ISSUE THREAD

**Issue by daisy1754** [react-native-community/react-native-image-picker#739]
### Description
On Android 6.0+, after user deny the permission request once, current behaviour is redirect users to app settings page (see below for detailed flow). The library should show system's permission request dialog unless user select 'never ask again'.

### How to repeat issue and example
1. Install Example app (and update compileSdk to 26) on Android 6.0+
2. Click 'select photo'
3. Deny permission request
4. Click 'select photo' again
5. Dialog to explain permission usage is shown. Click 'try again'
Expected:
permission request dialog is shown again
Actual: 
user is redirected to app settings

### Solution
will send a PR shortly

### Additional Information

* Platform: Android
* Development Operating System: MacOS
* Dev tools: Android SDK 26

**Comment by alreadysabbir** [comment]
@Agontuk have a look

**Comment by VizGhar** [comment]
There is a problem with usage of [`shouldShowRequestPermissionRationale()`](https://developer.android.com/reference/android/support/v4/app/ActivityCompat.html#shouldShowRequestPermissionRationale(android.app.Activity,%20java.lang.String)) method:

>  You should do this only if you do not have the permission and the context in which the permission is requested does not clearly communicate to the user what would be the benefit from granting this permission. 

I wouldn't use `shouldShowRequestPermissionRationale` at all. And show the "Permission denied" dialog from `onRequestPermissionsResult` method... (`Toast` should be even better, since user clicked "never show again", I don't see any point redirecting user to app settings)

**Comment by daisy1754** [comment]
Hi @VizGhar, to clarify, the issue I brought up is about user coming back second time after denying permission once. We could consider showing some UI in `onRequestPermissionsResult` as you suggest (I think the library may behave that way already - but my memory is vague as I haven't interact with this library for more than a month), but it doesn't solve my problem. 

Also friendly ping @marcshilling @yfuks - can anyone review my PR #740 ? It's been open for more than a month.

**Comment by marcshilling** [comment]
@daisy1754 as you can probably tell, I'm not actively maintaining this repo anymore. I handed it off to @haitaoli, but it's seemed to have died off.
