### ISSUE TITLE
iOS image not save 

### ISSUE THREAD

**Issue by callmejm** [react-native-community/react-native-image-picker#776]
In iOS, everything is fine except image not save. Camera capture and retrieve url to image component all fine. But when I check back to photo / gallery , captured photo are not there.

Options that I use : 

	var optionsIOS = {
	  title: 'Select Avatar',
	  cancelButtonTitle:'Cancel',
	  takePhotoButtonTitle:'Photo Capture',
	  chooseFromLibraryButtonTitle:'Choose from Gallery',
	  quality:0.5,
	  storageOptions: {
	    skipBackup: true,
	  }
	};

**Comment by ProteanDev** [comment]
@JayricMok I'm having the same issue. Did you have a solution?

**Comment by JayricMok** [comment]
@ProteanDev hi, i use the `cameraRoll` it saved but it have auto rotate issue then I use `waitUntilSaved`  solved my both issue

      storageOptions: {
        cameraRoll: true,
        skipBackup: true,
        waitUntilSaved:true
     }

**Comment by 729504321** [comment]
i have the same problem,try try try but don't work

**Comment by 729504321** [comment]
i see,thank you

**Comment by svenjungnickel** [comment]
Hello folks,

I had the same issue with images in iOS not saving to the device. Apparently its a permission problem since iOS version 10.

Regarding to the react native docs of [cameraroll|https://facebook.github.io/react-native/docs/cameraroll] you need to add two keys into the Info.plist of your project.

Add `NSPhotoLibraryUsageDescription` and/or `NSPhotoLibraryAddUsageDescription`, depending of the iOS version of your device. This added, you should get asked the first time you want to save images to your device. After granting access the image should be saved.

**Comment by jeffraux** [comment]
Any news on this? I'm also experiencing the same issue but mainly on iPad.
