### ISSUE TITLE
App Crashes After User Selects Photo / Video from the Gallery

### ISSUE THREAD

**Issue by rickcha** [react-native-community/react-native-image-picker#900]
On every **Samsung Galaxy S7 Active** device running **Android OS 8.0**, I've got a lot of app crash reports from our clients.

I tried upgrading the library to the latest, but I can't just seem to make it work in any way.

Looking at the bug tracking, it looks like the issue is really like the below.
`Caused By: java.lang.RuntimeException · android.database.sqlite.SQLiteException: no such column: cloud_server_id (code 1): , while compiling: SELECT _data FROM video WHERE (_id=?) ################################################################# Error Code : 1 (SQLITE_ERROR) Caused By : SQL(query) error or missing database. (no such column: cloud_server_id (code 1): , while compiling: SELECT _data FROM video WHERE (_id=?)) #################################################################
`

Here, I am providing the full log.
`java.lang.RuntimeException · Failure delivering result ResultInfo{who=null, request=13003, result=-1, data=Intent { dat=content://media/external/video/media/3864 flg=0x1 (has extras) }} to activity {com.vqa/com.vqa.MainActivity}: java.lang.RuntimeException: android.database.sqlite.SQLiteException: no such column: cloud_server_id (code 1): , while compiling: SELECT _data FROM video WHERE (_id=?) ################################################################# Error Code : 1 (SQLITE_ERROR) Caused By : SQL(query) error or missing database. (no such column: cloud_server_id (code 1): , while compiling: SELECT _data FROM video WHERE (_id=?)) #################################################################
ActivityThread.java:4491android.app.ActivityThread.deliverResults	
ActivityThread.java:4534android.app.ActivityThread.handleSendResult	
Unknownandroid.app.ActivityThread.-wrap20	
ActivityThread.java:1752android.app.ActivityThread$H.handleMessage	
Handler.java:105android.os.Handler.dispatchMessage	
Looper.java:164android.os.Looper.loop	
ActivityThread.java:6944android.app.ActivityThread.main	
Method.java:-2java.lang.reflect.Method.invoke	
Zygote.java:327com.android.internal.os.Zygote$MethodAndArgsCaller.run	
ZygoteInit.java:1374com.android.internal.os.ZygoteInit.main	
Caused By: java.lang.RuntimeException · android.database.sqlite.SQLiteException: no such column: cloud_server_id (code 1): , while compiling: SELECT _data FROM video WHERE (_id=?) ################################################################# Error Code : 1 (SQLITE_ERROR) Caused By : SQL(query) error or missing database. (no such column: cloud_server_id (code 1): , while compiling: SELECT _data FROM video WHERE (_id=?)) #################################################################
ReactContext.java:311com.facebook.react.bridge.ReactContext.handleException	
ReactContext.java:255com.facebook.react.bridge.ReactContext.onActivityResult	
ReactInstanceManager.java:692com.facebook.react.ReactInstanceManager.onActivityResult	
ReactActivityDelegate.java:126com.facebook.react.ReactActivityDelegate.onActivityResult	
ReactActivity.java:75com.facebook.react.ReactActivity.onActivityResult	
Activity.java:7547android.app.Activity.dispatchActivityResult	
ActivityThread.java:4487android.app.ActivityThread.deliverResults	
ActivityThread.java:4534android.app.ActivityThread.handleSendResult	
Unknownandroid.app.ActivityThread.-wrap20	
ActivityThread.java:1752android.app.ActivityThread$H.handleMessage	
Handler.java:105android.os.Handler.dispatchMessage	
Looper.java:164android.os.Looper.loop	
ActivityThread.java:6944android.app.ActivityThread.main	
Method.java:-2java.lang.reflect.Method.invoke	
Zygote.java:327com.android.internal.os.Zygote$MethodAndArgsCaller.run	
ZygoteInit.java:1374com.android.internal.os.ZygoteInit.main	
Caused By: android.database.sqlite.SQLiteException · no such column: cloud_server_id (code 1): , while compiling: SELECT _data FROM video WHERE (_id=?) ################################################################# Error Code : 1 (SQLITE_ERROR) Caused By : SQL(query) error or missing database. (no such column: cloud_server_id (code 1): , while compiling: SELECT _data FROM video WHERE (_id=?)) #################################################################
DatabaseUtils.java:179android.database.DatabaseUtils.readExceptionFromParcel	
DatabaseUtils.java:135android.database.DatabaseUtils.readExceptionFromParcel	
ContentProviderNative.java:418android.content.ContentProviderProxy.query	
ContentResolver.java:760android.content.ContentResolver.query	
ContentResolver.java:710android.content.ContentResolver.query	
ContentResolver.java:668android.content.ContentResolver.query	
RealPathUtil.java:132com.imagepicker.utils.RealPathUtil.getDataColumn	
RealPathUtil.java:102com.imagepicker.utils.RealPathUtil.getRealPathFromURI	
ImagePickerModule.java:635com.imagepicker.ImagePickerModule.getRealPathFromURI	
ImagePickerModule.java:412com.imagepicker.ImagePickerModule.onActivityResult	
ReactContext.java:253com.facebook.react.bridge.ReactContext.onActivityResult	
ReactInstanceManager.java:692com.facebook.react.ReactInstanceManager.onActivityResult	
ReactActivityDelegate.java:126com.facebook.react.ReactActivityDelegate.onActivityResult	
ReactActivity.java:75com.facebook.react.ReactActivity.onActivityResult	
Activity.java:7547android.app.Activity.dispatchActivityResult	
ActivityThread.java:4487android.app.ActivityThread.deliverResults	
ActivityThread.java:4534android.app.ActivityThread.handleSendResult	
Unknownandroid.app.ActivityThread.-wrap20	
ActivityThread.java:1752android.app.ActivityThread$H.handleMessage	
Handler.java:105android.os.Handler.dispatchMessage	
Looper.java:164android.os.Looper.loop	
ActivityThread.java:6944android.app.ActivityThread.main	
Method.java:-2java.lang.reflect.Method.invoke	
Zygote.java:327com.android.internal.os.Zygote$MethodAndArgsCaller.run	
ZygoteInit.java:1374com.android.internal.os.ZygoteInit.main`

Please help us as most of our users have S7 Active devices running Android 8.0..

Thank you in advance.

**Comment by maac4422** [comment]
Are you using sqlite? The error is.
(SQLITE_ERROR) Caused By : SQL(query) error or missing database. (no such column: cloud_server_id (code 1): , while compiling: SELECT _data FROM video WHERE (_id=?)) 
Are you sure that error is from the library?

**Comment by AmandeepSingh06** [comment]
I am facing a similar exception

Caused by java.lang.IllegalArgumentException

android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:165)
android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:135)
android.content.ContentProviderProxy.query (ContentProviderNative.java:418)
android.content.ContentResolver.query (ContentResolver.java:756)
android.content.ContentResolver.query (ContentResolver.java:705)
android.content.ContentResolver.query (ContentResolver.java:663)
com.imagepicker.utils.RealPathUtil.getDataColumn (RealPathUtil.java:132)
com.imagepicker.utils.RealPathUtil.getRealPathFromURI (RealPathUtil.java:102)
com.imagepicker.ImagePickerModule.getRealPathFromURI (ImagePickerModule.java:635)
com.imagepicker.ImagePickerModule.onActivityResult (ImagePickerModule.java:386)
com.facebook.react.bridge.ReactContext.onActivityResult (ReactContext.java:255)
com.facebook.react.ReactInstanceManager.onActivityResult (ReactInstanceManager.java:730)
com.facebook.react.ReactActivityDelegate.onActivityResult (ReactActivityDelegate.java:126)
com.facebook.react.ReactActivity.onActivityResult (ReactActivity.java:77)
android.app.Activity.dispatchActivityResult (Activity.java:7357)
android.app.ActivityThread.deliverResults (ActivityThread.java:4311)
android.app.ActivityThread.handleSendResult (ActivityThread.java:4359)
android.app.ActivityThread.-wrap19 (Unknown Source)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1669)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:171)
android.app.ActivityThread.main (ActivityThread.java:6622)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:518)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:824)

Any idea what is causing this crash. Getting this crash on Xiaomi android device running Oreo.

**Comment by jfbaraky** [comment]
Having the same error on a Sansung Galaxy S9+

**Comment by evanjmg** [comment]
+1 - it shouldn't crash - it should error

**Comment by akhileshagrhari** [comment]
Same issue on samsung galaxy j3. on other phone, the library is working fine.

**Comment by evanjmg** [comment]
this fixes the video case for me - https://github.com/react-native-community/react-native-image-picker/pull/1049

**Comment by kranthijulakantiwork** [comment]
is this issue fixed, I am still facing this issue with "react-native-image-picker": "0.28.0"

**Comment by evanjmg** [comment]
@kranthijulakantiwork  please fork my PR and thumb up if it works for you so we can get it merged - https://github.com/react-native-community/react-native-image-picker/pull/1049

**Comment by kranthijulakantiwork** [comment]
@evanjmg I checked with your forked repo, but still facing the same issue

**Comment by evanjmg** [comment]
This is still an issue - awaiting feedback on PR here- #1049
