### ISSUE TITLE
Cannot read property 'showImagePicker' of undefined on Android

### ISSUE THREAD

**Issue by xfan0516** [react-native-community/react-native-image-picker#957]
* Please read the following carefully before opening a new issue.
##### Before the problem:  
Undefined is not an object (evaluating 'ImagePickerManager.showImagePicker')
##### Follow the links below:
[https://github.com/react-community/react-native-image-picker/issues/609](https://github.com/react-community/react-native-image-picker/issues/609)
###### Then there's the following problem:
![screenshot_2018-10-15-09-56-55](https://user-images.githubusercontent.com/33110460/46925842-c7a95000-d060-11e8-939a-b36a3e7ad867.png)

react-native: 0.55.2
react-native-image-picker 0.27.1
jest-expo: 27.0.0

**Comment by wzup** [comment]
Not only Android. iOS doesn't work too.

https://github.com/react-community/react-native-image-picker/issues/963
https://github.com/react-community/react-native-image-picker/issues/962

**Comment by mfferreira** [comment]
bump

**Comment by kaushal9678** [comment]
I fix this using the following steps
**1. Add RNImagePicker from node_modules to Xcode
2. Then drag libRNImagePicker.a to Build Phases -> Link Binary with Libraries
3. After doing this go to build settings-> Header Search path and add the following line so that it will look for this library
**$(SRCROOT)/../node_modules/react-native-image-picker/ios**
4. Clean your project
5. Build your project and Run
It will run successfully.
 **Check enclosed image****

![simulator screen shot - iphone x - 2019-02-28 at 11 46 12](https://user-images.githubusercontent.com/4991337/53545155-8799c400-3b4e-11e9-9c6b-41198657f431.png)

**Comment by Cumbermiao** [comment]
Did you run react-native link react-native-image-picker ?

**Comment by kaushal9678** [comment]
@cumbermiao, yes I ran that command so that it can link modules on both platform but for iOS you have to do it also manual linking.

Other alternative is not run this command bcoz we have to do manual linking in ios then we can also do the same for Android.
